### PR TITLE
Add deprecate warnings for Terra.it helpers

### LINKED ISSUE #62: Add Deprecation to Terra.it helpers
# Feature Request

## Description
`Terra.it` helpers are going away. Add deprecation warning to `Terra.it` helpers and add guidance on how to migrate users to use the `Terra.validates` helpers within their own `it` blocks.

### PR DESCRIPTION
**Pull request by benbcai**
### Summary
Add deprecate warnings for `Terra.it.*` helpers. Recommendation is to use the `Terra.validate.*` counterparts inside a mocha `it` block.

Closes #62 

### Additional Details
Initially we talked about just printing the warning each time the deprecated method is used. This is how it can look like which is quite excessive considering the deprecating `Terra.it.*` helpers are more widely used than the recommended `Terra.validate.*` helpers.

**Should we consider printing it just once per test or test suite in the `beforeTest` or `beforeSuite` hook?**

```
․․․․․[Terra-Toolkit:terra-service] Terra.it.isAccessible is deprecated. Please use Terra.validates.accessibility inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.isAccessible is deprecated. Please use Terra.validates.accessibility inside an `it` block.
․․․․․․․․․․․․․[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
․․․․․․․․․․․․․․․․[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
[Terra-Toolkit:terra-service] Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block.
```

### CODE REVIEW

**Review by emilyrohrbough — APPROVED** [review]

**Review by yuderekyu — COMMENTED** [review]
would it be more useful to also output the line number for each helper call? would that greatly increase the scope of this? i took a quick look and see that creating an error exposes the stack trace details, but it might be too much of a hassle

**Comment by ShettyAkarsh** [comment]
so instead of printing the same message multiple times can we print the deprecation message like this ?

'Terra.it.matchesScreenshot is deprecated. Please use Terra.validates.screenshot inside an `it` block. changes needs to be done in the following files and the line numbers mentioned below.'

specfile1 :-  line1, line4 .......... etc
specfile2 :- line4, line 5............ etc

**Comment by benbcai** [comment]
@yuderekyu @ShettyAkarsh The detection takes place when consumers are calling any of the deprecating `Terra.it.*` commands. Printing all of that at the end of the test can be done but I don't know of a way to determine which file or line is calling these commands. Do you have any suggestion?

One way could be to parse the entire project but that is probably not what we want to do as part of this.

**Review by StephenEsser — APPROVED** [review]

**Review by mjhenkes — APPROVED** [review]

**Review by yuderekyu — APPROVED** [review]
line numbers is a nice to have, but i'm cool not having it

**Pull request merged**
